---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  network:
    - - forwarded_port
      - guest: 8980
        host: 8980
        auto_correct: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    attributes:
      opennms:
        home: /usr/share/opennms

  - name: centos-7.0
    attributes:
      opennms:
        home: /opt/opennms

suites:
  - name: default
    run_list:
      - recipe[opennms-light::default]
    attributes:
      ubuntu:
        archive_url: http://de.archive.ubuntu.com/ubuntu
      opennms:
        release: stable

  - name: remote-poller
    run_list:
      - recipe[opennms-light::remote-poller]
    attributes:
      ubuntu:
        archive_url: http://de.archive.ubuntu.com/ubuntu
      opennms:
        release: stable
        home: /usr/share/opennms
        location: Germany
        baseurl: http://192.168.0.1:8980/opennms-remoting
