---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  network:
    - - forwarded_port
      - guest: 8980
        host: 8980
        auto_correct: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    attributes:
      opennms:
        home: /usr/share/opennms

  - name: ubuntu-12.04
    attributes:
      opennms:
        home: /usr/share/opennms

  - name: centos-6.5
    attributes:
      opennms:
        home: /opt/opennms

  - name: centos-7.0
    attributes:
      opennms:
        home: /opt/opennms

suites:
  - name: default
    run_list:
      - recipe[opennms-light::default]
    attributes:
      opennms:
        release: snapshot
        repository:
          yum: yum.opennms.eu
          apt: debian.opennms.eu
 
  - name: remote-poller
    run_list:
      - recipe[java]
      - recipe[opennms-light::remote-poller]
    attributes:
      java:
        install_flavor: openjdk
        jdk_version: 7
      opennms:
        release: stable
        home: /usr/share/opennms
        location: Germany
        baseurl: http://192.168.0.1:8980/opennms-remoting
        repository:
          yum: yum.opennms.eu
          apt: debian.opennms.eu

